[[ -f ~/.profile ]] && . ~/.profile

. ~/.zshrc-grml

PATH="${HOME}/opt/bin:${PATH}"

HISTFILE=~/.histfile
HISTSIZE=1000
SAVEHIST=1000
setopt appendhistory beep notify
bindkey -e

which yay &>/dev/null && alias yay='sudo -u builder yay'
which yay &>/dev/null && alias yayinst='sudo -u builder yay -Syu --needed'

alias bashtrace="PS4='+(\${BASH_SOURCE}:\${LINENO}): \${FUNCNAME[0]:+\${FUNCNAME[0]}(): }' bash -x"

[[ -f ~/.zshrc-local ]] && . ~/.zshrc-local

true
